name: Linting checks

on:
  pull_request:
    branches:
      - '**'  

jobs:
  make-check:
    runs-on: [self-hosted, linux, X64, codeql]

    steps:    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Build Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Install dependencies
      run: |
        make virtualenv
        python -m pip install --upgrade pip  
        pip install ruff black isort

    - name: Run Make Check
      run: make check
